In [1]:
import numpy as np

# Creating the matrix M
M = np.array([[1, 0, 3],
              [3, 7, 2],
              [2, -2, 8],
              [0, -1, 1],
              [5, 8, 7]])

# Compute M^T M
MTM = np.dot(M.T, M)

# Compute M M^T
MMT = np.dot(M, M.T)

print("Matrix M^T M:\n", MTM)
print("Matrix M M^T:\n", MMT)

Matrix M^T M:
 [[ 39  57  60]
 [ 57 118  53]
 [ 60  53 127]]
Matrix M M^T:
 [[ 10   9  26   3  26]
 [  9  62   8  -5  85]
 [ 26   8  72  10  50]
 [  3  -5  10   2  -1]
 [ 26  85  50  -1 138]]


In [2]:
# Eigenvalues for M^T M
eigenvalues_MTM, _ = np.linalg.eig(MTM)
print("Eigenvalues of M^T M:", eigenvalues_MTM)

# Eigenvalues for M M^T
eigenvalues_MMT, _ = np.linalg.eig(MMT)
print("Eigenvalues of M M^T:", eigenvalues_MMT)

Eigenvalues of M^T M: [ 2.14670489e+02 -1.33871866e-14  6.93295108e+01]
Eigenvalues of M M^T: [ 2.14670489e+02 -4.13378832e-15  6.93295108e+01 -3.28163351e-15
 -4.10937465e-16]


In [3]:
# Eigenvectors for M^T M
_, eigenvectors_MTM = np.linalg.eig(MTM)
print("Eigenvectors of M^T M:\n", eigenvectors_MTM)

# Eigenvectors for M M^T
_, eigenvectors_MMT = np.linalg.eig(MMT)
print("Eigenvectors of M M^T:\n", eigenvectors_MMT)

Eigenvectors of M^T M:
 [[ 0.42615127  0.90453403 -0.01460404]
 [ 0.61500884 -0.30151134 -0.72859799]
 [ 0.66344497 -0.30151134  0.68478587]]
Eigenvectors of M M^T:
 [[-0.16492942 -0.95539856  0.24497323 -0.83645189  0.14590955]
 [-0.47164732 -0.03481209 -0.45330644  0.32249423 -0.1726319 ]
 [-0.33647055  0.27076072  0.82943965  0.40049076  0.06871429]
 [-0.00330585  0.04409532  0.16974659 -0.03474164 -0.97055978]
 [-0.79820031  0.10366268 -0.13310656 -0.18640247  0.04691152]]


In [4]:
# Singular values from the nonzero eigenvalues of MTM
singular_values = np.sqrt(eigenvalues_MTM[eigenvalues_MTM > 1e-10])  # Applying a threshold for numerical stability

# Constructing Sigma
Sigma = np.diag(singular_values)

# Constructing U and V (Using only the first two eigenvectors corresponding to the nonzero eigenvalues)
U = eigenvectors_MMT[:, :2]
V = eigenvectors_MTM[:, :2]

print("Matrix U:\n", U)
print("Matrix Sigma:\n", Sigma)
print("Matrix V:\n", V)


Matrix U:
 [[-0.16492942 -0.95539856]
 [-0.47164732 -0.03481209]
 [-0.33647055  0.27076072]
 [-0.00330585  0.04409532]
 [-0.79820031  0.10366268]]
Matrix Sigma:
 [[14.65163776  0.        ]
 [ 0.          8.32643446]]
Matrix V:
 [[ 0.42615127  0.90453403]
 [ 0.61500884 -0.30151134]
 [ 0.66344497 -0.30151134]]


In [5]:
# Keep only the largest singular value
Sigma_1D = np.diag([singular_values[0], 0])

# Approximate M in 1D
M_approx_1D = np.dot(U, np.dot(Sigma_1D, V.T))

print("One-dimensional approximation of M:\n", M_approx_1D)


One-dimensional approximation of M:
 [[-1.02978864 -1.48616035 -1.60320558]
 [-2.94487812 -4.24996055 -4.58467382]
 [-2.10085952 -3.031898   -3.27068057]
 [-0.02064112 -0.02978864 -0.0321347 ]
 [-4.9838143  -7.19249261 -7.75895028]]
